### ISSUE TITLE
Util Load 함수 위치 변경

### ISSUE THREAD

**Issue by alstnkim** [2023OSS-Team5-Project/Team5-Miniproject#16]
Manager Mode에서 사용하는 데이터 타입은 pointer Array Type인데 User Mode에서 사용하는 데이터 타입은 Array Type이라 Load 함수를 Util에 넣어 동시에 사용하는 것이 어렵다고 생각합니다. Manager Mode와 User Mode에서 각각 Load 함수를 정의하여 사용하는 것은 어떻게 생각하시나요?

**Comment by Woochal** [comment]
User mode에서도 pointer array로 사용하고 있습니다. 

포인터 변수를 생성하고 malloc을 통해서 포인터 배열로 사용하고 있어요.

**Comment by alstnkim** [comment]
알겠습니다
