### ISSUE TITLE
매니저 모드 메뉴 간격 맞춤

### ISSUE THREAD

**Issue by Woochal** [2023OSS-Team5-Project/Team5-Miniproject#26]
https://kthan.tistory.com/entry/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8DC-%EB%8B%A4%EC%96%91%ED%95%9C-%ED%98%95%EC%8B%9D%EC%9D%98-printf%EB%AC%B8-%EC%A0%95%EB%A0%AC-%EB%B0%A9%EB%B2%95

해당 블로그와 유저 모드 참고하시면 다음과 같이 만들 수 있습니다.

![image](https://github.com/2023OSS-Team5-Project/Team5-Miniproject/assets/112460787/c2261a19-9630-40b7-ac7a-59fcb1b51997)

**Comment by alstnkim** [comment]
알겠습니다! 감사합니다!!
