### ISSUE TITLE
컴파일 시 한글 깨짐 현상

### ISSUE THREAD

**Issue by Woochal** [2023OSS-Team5-Project/Team5-Miniproject#4]
메인 브랜치의 파일들을 로컬로 다운 받은 후 작업하려고 테스트 컴파일을 했을 때 한글이 깨지는 현상이 일어납니다.

https://rasino.tistory.com/343

해당 블로그를 참고하여 encoding 설정 등을 해보고

혹시나 맥과 윈도우 os 차이 때문인가 싶어서 윈도우 환경에서 테스트 해봐도 똑같이 한글이 깨지는 현상이 발생합니다.

Github에서 코드를 확인할 때도 마찬가지인것 같습니다.

**Comment by alstnkim** [comment]
인코딩을 KR로 변경해도 깨지나요?

**Comment by alstnkim** [comment]
우선 개인의 컴퓨터에서 작동하는 방식으로 진행하고 나중에 마무리 단계에서 해결하는 걸로 해요!

**Comment by alstnkim** [comment]
영어로 변경하여 작업 부탁드립니다! 추후에 한글로 수정하는 걸로 해요!

**Comment by Woochal** [comment]
혹시나 해서 마지막으로 윈도우 세팅을 설정해 보니, 컴파일 시에 정상적으로 출력이 되는 것 같습니다.

**Comment by Woochal** [comment]
EUC-KR로 작업하고 Push 했을 때 제가 올린 파일을 Github 에서 확인하면 한글이 잘 출력되는데 다른 사람이 올린것은 깨지는 경우는 무엇일까요?

같은 OS면 encoding 방식이 차이가 있을 것 같진 않은데... 학우님도 EUC-KR로 작업하신거 아닌가요?

**Comment by Woochal** [comment]
github에서 euc-kr 인코딩을 지원하지 않아서 push 전 utf-8로 push 하고, pull 이후에 euc-kr로 변경 후 작업하는 것으로 해결
